import {
  Box,
  Button,
  Heading,
  HStack,
  Image,
  useInputChange,
  VStack,
} from '@holdr-ui/react';
import {
  InputTextField,
  makeButtonLarger,
  makePath,
  Paths,
  Stepper,
  StepperStep,
  TextGroup,
  TextGroupHeading,
  TextGroupSubheading,
  useStepperContext,
} from '../../../../shared';
import { useLocation, useNavigate } from 'react-router-dom';

enum Setup2FAStep {
  Overview,
  Update,
  Verification,
}

function Setup2FAPageOverviewStep() {
  const location = useLocation();
  const navigate = useNavigate();

  const { increment } = useStepperContext();

  return (
    <VStack flex={1} px={5} pb={5}>
      <TextGroup>
        <TextGroupHeading as='h2' weight={500} size={3}>
          Get started
        </TextGroupHeading>
        <TextGroupSubheading size={2} color='white700'>
          Protect your account in two easy steps
        </TextGroupSubheading>
      </TextGroup>
      <VStack flex={1} justify='space-between'>
        <VStack mt={10} gap={8}>
          <HStack items='flex-start' gap={3}>
            <Image
              size={75}
              radius={1}
              css={{
                background: 'rgba(152, 152, 255, 0.15)',
                flexShrink: 0,
              }}
            />
            <TextGroup gap={0}>
              <TextGroupHeading
                size={3}
                as='h5'
                css={{ lineHeight: '150%' }}
              >
                Use authentication app
              </TextGroupHeading>
              <TextGroupSubheading size={2} color='white700' weight={500}>
                Scan the QR Code that we generate for you using a secure
                authenticator (Google or any other).
              </TextGroupSubheading>
            </TextGroup>
          </HStack>
          <HStack items='flex-start' gap={3}>
            <Image
              size={75}
              radius={1}
              css={{
                background: 'rgba(152, 152, 255, 0.15)',
                flexShrink: 0,
              }}
            />
            <TextGroup gap={0}>
              <TextGroupHeading
                size={3}
                as='h5'
                css={{ lineHeight: '150%' }}
              >
                Enter confirmation code
              </TextGroupHeading>
              <TextGroupSubheading size={2} color='white700' weight={500}>
                Two-factor authentication will be enabled once the code
                generated by the authenticator app is entered and
                confirmed. It can be turned off at any time.
              </TextGroupSubheading>
            </TextGroup>
          </HStack>
        </VStack>
        <HStack
          justify='flex-end'
          borderTop={1}
          borderColor='rgba(152, 152, 255, 0.1)'
          pt={5}
          gap={5}
        >
          <Button
            onClick={() =>
              navigate(
                location.state.previousLocation ??
                  makePath([Paths.settings, Paths.setting.account]),
              )
            }
            variant='ghost'
            colorTheme='white700'
            className={makeButtonLarger('2.75rem')}
            css={{ px: '$8', py: '$4', border: 'unset' }}
            radius={1}
          >
            Cancel
          </Button>
          <Button
            onClick={increment}
            colorTheme='purple500'
            className={makeButtonLarger('2.75rem')}
            css={{ px: '$8', py: '$4' }}
            radius={1}
          >
            Setup 2FA
          </Button>
        </HStack>
      </VStack>
    </VStack>
  );
}

function Setup2FAVerificationStep() {
  const location = useLocation();
  const navigate = useNavigate();

  const { value, handleOnChange } = useInputChange('');

  const { decrement } = useStepperContext();

  return (
    <VStack flex={1} px={5} pb={5}>
      <TextGroup gap={0}>
        <TextGroupHeading as='h2' weight={500} size={3}>
          Verify Code
        </TextGroupHeading>
        <TextGroupSubheading size={2} color='white700'>
          Enter the code that has been sent to the phone number that you
          provided and we will confirm your identity.
        </TextGroupSubheading>
      </TextGroup>
      <VStack
        as='form'
        mt={8}
        onSubmit={async (e) => {
          e.preventDefault();

          navigate(
            location.state.previousLocation ??
              makePath([Paths.settings, Paths.setting.account]),
          );
        }}
        flex={1}
        justify='space-between'
      >
        <InputTextField
          value={value}
          onChange={handleOnChange}
          name='code'
          label='Enter verification code'
        />
        <HStack
          justify='flex-end'
          borderTop={1}
          borderColor='rgba(152, 152, 255, 0.1)'
          pt={5}
          gap={5}
        >
          <Button
            onClick={decrement}
            variant='ghost'
            colorTheme='white700'
            className={makeButtonLarger('2.75rem')}
            css={{ px: '$8', py: '$4', border: 'unset' }}
            radius={1}
          >
            Back
          </Button>
          <Button
            onClick={() =>
              navigate(
                location.state.previousLocation ??
                  makePath([Paths.settings, Paths.setting.account]),
              )
            }
            colorTheme='purple500'
            className={makeButtonLarger('2.75rem')}
            css={{ px: '$8', py: '$4' }}
            radius={1}
          >
            Verify
          </Button>
        </HStack>
      </VStack>
    </VStack>
  );
}

function Setup2FAScanStep() {
  const { value, handleOnChange } = useInputChange('');

  const { increment, decrement } = useStepperContext();

  return (
    <VStack flex={1} px={5} pb={5}>
      <TextGroup gap={0}>
        <TextGroupHeading as='h2' weight={500} size={3}>
          Update your phone number
        </TextGroupHeading>
        <TextGroupSubheading size={2} color='white700'>
          Enter the code that has been sent to the phone number that you
          provided and we will confirm your identity.
        </TextGroupSubheading>
      </TextGroup>
      <VStack
        as='form'
        mt={8}
        onSubmit={async (e) => {
          e.preventDefault();
          increment();
        }}
        flex={1}
        justify='space-between'
      >
        <HStack
          justify='flex-end'
          borderTop={1}
          borderColor='rgba(152, 152, 255, 0.1)'
          pt={5}
          gap={5}
        >
          <Button
            onClick={decrement}
            variant='ghost'
            colorTheme='white700'
            className={makeButtonLarger('2.75rem')}
            css={{ px: '$8', py: '$4', border: 'unset' }}
            radius={1}
          >
            Back
          </Button>
          <Button
            onClick={increment}
            colorTheme='purple500'
            className={makeButtonLarger('2.75rem')}
            css={{ px: '$8', py: '$4' }}
            radius={1}
          >
            Continue
          </Button>
        </HStack>
      </VStack>
    </VStack>
  );
}

function Setup2FAPage() {
  return (
    <VStack
      h={600}
      gap={4}
      divider={<Box h='1px' w='full' bgColor='rgba(152, 152, 255, 0.1)' />}
    >
      <Box px={5} pt={5}>
        <Heading size={6} weight={500}>
          Authentication App
        </Heading>
      </Box>
      <Stepper>
        <StepperStep step={Setup2FAStep.Overview}>
          <Setup2FAPageOverviewStep />
        </StepperStep>
        <StepperStep step={Setup2FAStep.Update}>
          <Setup2FAScanStep />
        </StepperStep>
        <StepperStep step={Setup2FAStep.Verification}>
          <Setup2FAVerificationStep />
        </StepperStep>
      </Stepper>
    </VStack>
  );
}

export default Setup2FAPage;
