version: "3.8"

name: "holdr-web-app"

services:
  web-app:
    container_name: holdr_web_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    env_file:
      - .env
    restart: unless-stopped
    command: ["yarn", "dev"]