export { default as SettingsRoutes } from './settings.routes';
export { default as UserRoutes } from './user.routes';
export { default as BookmarksRoutes } from './bookmarks.routes';
export { default as MessagesRoutes } from './messages.routes';
export { default as ReleasesRoutes } from './releases.routes';
export { default as SetupFlowRoutes } from './setup-flow.routes';
export { default as ConnectRoutes } from './connect.routes';
export { default as ClubRoutes } from './club.routes';
export { default as SetupProfileRoutes } from './setup-profile.routes';
