name: Lint, Test and build

on: [ push, pull_request ]

jobs:
  build:
    name: Build, lint, and test on Node

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '16x', '18.x' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build